<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TG48D8J" failures="0" tests="1" name="ds_algo.ObjectTest" time="2.791" errors="1" timestamp="2022-10-15T14:44:35 EDT" skipped="0">
  <testcase classname="ds_algo.ObjectTest" name="verifyObject" time="2.791">
    <error message="Unresolved compilation problems: 
	The annotation @FindBy is disallowed for this location
	The annotation @FindBy is disallowed for this location
	The annotation @FindBy is disallowed for this location
	The annotation @FindBy is disallowed for this location
	GetStart cannot be resolved
	HomePage cannot be resolved
	DataStructures cannot be resolved
	GetStarted cannot be resolved
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
The annotation @FindBy is disallowed for this location
The annotation @FindBy is disallowed for this location
The annotation @FindBy is disallowed for this location
The annotation @FindBy is disallowed for this location
GetStart cannot be resolved
HomePage cannot be resolved
DataStructures cannot be resolved
GetStarted cannot be resolved

at ds_algo.RegestraionPage.<init>(RegestraionPage.java:18)
at ds_algo.ObjectTest.verifyObject(ObjectTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyObject -->
  <system-out/>
</testsuite> <!-- ds_algo.ObjectTest -->
